### ISSUE TITLE
expo-barcode-generator not compatible with Expo SDK 52

### ISSUE THREAD

**Issue by martinch92** [nmamali/expo-barcode-generator#9]
The expo-barcode-generator package is breaking when used with Expo SDK 52. This issue might be due to compatibility problems introduced by updates in the latest SDK. The barcode  throws errors, making the package unusable in projects using Expo 52.

**Comment by JPStrydom** [comment]
@martinch92 and @illud [version 4.0.0](https://www.npmjs.com/package/expo-barcode-generator) should be compatible with Expo 52. Thanks for your patience. 

Please let us know if you're still experiencing issues after upgrading.
